require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JobScoresController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # JobScore. As you add validations to JobScore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JobScoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all job_scores as @job_scores" do
      job_score = JobScore.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:job_scores)).to eq([job_score])
    end
  end

  describe "GET #show" do
    it "assigns the requested job_score as @job_score" do
      job_score = JobScore.create! valid_attributes
      get :show, {:id => job_score.to_param}, valid_session
      expect(assigns(:job_score)).to eq(job_score)
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested job_score" do
      job_score = JobScore.create! valid_attributes
      expect {
        delete :destroy, {:id => job_score.to_param}, valid_session
      }.to change(JobScore, :count).by(-1)
    end

    it "redirects to the job_scores list" do
      job_score = JobScore.create! valid_attributes
      delete :destroy, {:id => job_score.to_param}, valid_session
      expect(response).to redirect_to(job_scores_url)
    end
  end

end
